version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: app_asset
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shared-networks

volumes:
  mysql-data:

networks:
  shared-networks:
    external: true
